sudo: required

services:
  - docker

env:
  global:
    - SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
    - INSTALL_DIR=$HOME/google-cloud-sdk
    - PROJECT_ID=fincalc-430420
    - CLUSTER_NAME=autopilot-cluster-1
    - CLOUDSDK_COMPUTE_ZONE=us-central1
    - GCLOUD_SERVICE_KEY=${GCLOUD_SERVICE_KEY}

before_install:
  - openssl aes-256-cbc -K $encrypted_9f3b5599b056_key -iv $encrypted_9f3b5599b056_iv -in service-account.json.enc -out service-account.json -d
  - curl https://sdk.cloud.google.com > install.sh
  - bash install.sh --disable-prompts --install-dir=$INSTALL_DIR
  - export PATH=${INSTALL_DIR}/google-cloud-sdk/bin:${PATH}
  - gcloud --quiet components install kubectl
  - gcloud auth activate-service-account --key-file service-account.json
  - gcloud --quiet config set project ${PROJECT_ID}
  - gcloud --quiet config set container/cluster ${CLUSTER_NAME}
  - gcloud --quiet config set compute/zone ${CLOUDSDK_COMPUTE_ZONE}
  - gcloud --quiet container clusters get-credentials ${CLUSTER_NAME}
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t itsmesohit/client-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true itsmesohit/client-test npm test

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: main
