sudo: required

services:
  - docker

env:
  global:
    - SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
    - CLOUDSDK_PYTHON=/usr/bin/python3.8

before_install:
  # Install Python 3.8
  - sudo apt-get update
  - sudo apt-get install -y python3.8 python3.8-venv python3.8-dev

  # Decrypt the service account JSON
  - openssl aes-256-cbc -K $encrypted_9f3b5599b056_key -iv $encrypted_9f3b5599b056_iv -in service-account.json.enc -out service-account.json -d

  # Install Google Cloud SDK
  - curl https://sdk.cloud.google.com | bash > /dev/null
  - source $HOME/google-cloud-sdk/path.bash.inc

  # Update kubectl component
  - gcloud components update kubectl

  # Authenticate and configure gcloud
  - gcloud auth activate-service-account --key-file service-account.json
  - gcloud config set project fincalc-430420
  - gcloud config set compute/zone us-central1
  - gcloud container clusters get-credentials autopilot-cluster-1
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t itsmesohit/client-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true itsmesohit/client-test npm test

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: main