sudo: required

services:
  - docker

env:
  global:
    - SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1

before_install:
  - docker pull python:3.9
  - docker run -v $PWD:/workspace -w /workspace python:3.9 bash -c "
      curl https://sdk.cloud.google.com | bash;
      source $HOME/google-cloud-sdk/path.bash.inc;
      gcloud components update kubectl;
      gcloud auth activate-service-account --key-file service-account.json;
      gcloud config set project fincalc-430420;
      gcloud config set compute/zone us-central1;
      gcloud container clusters get-credentials autopilot-cluster-1;
      echo \"$DOCKER_PASSWORD\" | docker login -u \"$DOCKER_USERNAME\" --password-stdin;
      docker build -t itsmesohit/client-test -f ./client/Dockerfile.dev ./client;
      docker run -e CI=true itsmesohit/client-test npm test;
      bash ./deploy.sh;
    "

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: main
