sudo: required

services:
  - docker

before_install:
  - docker pull python:3.9
  
install:
  - |
    if [ ! -d "$HOME/google-cloud-sdk" ]; then
      curl https://sdk.cloud.google.com | bash;
    else
      echo "Google Cloud SDK is cached";
    fi
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file service-account.json
  - gcloud config set project fincalc-430420
  - gcloud config set compute/zone us-central1
  - gcloud container clusters get-credentials autopilot-cluster-1

script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t itsmesohit/client-test -f ./client/Dockerfile.dev ./client
  - docker run -e CI=true itsmesohit/client-test npm test

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: main

cache:
  directories:
    - $HOME/google-cloud-sdk

timeout:
  - 30
