sudo: required

services:
  - docker

before_install:
  # Pull the Python Docker image
  - docker pull python:3.9
  
install:
  # Install Google Cloud SDK and Docker CLI
  - curl https://sdk.cloud.google.com | bash
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file service-account.json
  - gcloud config set project fincalc-430420
  - gcloud config set compute/zone us-central1
  - gcloud container clusters get-credentials autopilot-cluster-1
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

script:
  # Build Docker image
  - docker build -t itsmesohit/client-test -f ./client/Dockerfile.dev ./client
  # Run tests
  - docker run -e CI=true itsmesohit/client-test npm test

deploy:
  # Deploy using deploy.sh
  provider: script
  script: bash ./deploy.sh
  on:
    branch: main
