apiVersion: cert-manager.io/v1
 
kind: Certificate
metadata:
  name: itsmesohit-in-tls
spec:
  secretName: itsmesohit-in
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: itsmesohit.in
  dnsNames:
    - itsmesohit.in
    - www.itsmesohit.in